name: Deploy App with Helm + EKS
on:
  workflow_run:
    workflows: ["Terraform Infrastructure"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::831274730062:role/github-actions-role
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Sleep to allow IAM propagation
        run: |
          echo "Waiting 30 seconds to allow IAM changes to propagate..."
          sleep 30

      - name: Verify assumed role identity
        run: aws sts get-caller-identity

      - name: Update kubeconfig (requires AWS creds)
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name secure_cluster

      - name: Clear AWS credentials to force OIDC
        run: |
          echo "Clearing AWS credentials to test OIDC-based kubectl..."
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN

      - name: Who am I according to kubectl (OIDC)
        run: |
          kubectl config view --minify
          kubectl config current-context
          aws sts get-caller-identity

      - name: Test kubectl access
        run: kubectl get nodes
         
      

      