name: Terraform Infrastructure 
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
      branches:
      - main
      paths:
      - 'terraform/**'
  workflow_dispatch:

env: 
  TF_WORKING_DIR: ./terraform
  PUBLIC_ACCESS_CIDRS: '["73.122.229.85/32"]'
  ACTIONS_ROLE_ARN: ${{ secrets.ACTIONS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:  
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -no-color -out=tfplan -input=false \
            -var="public_access_cidrs=${PUBLIC_ACCESS_CIDRS}" \
            -var="github_actions_role_arn=${ACTIONS_ROLE_ARN}" || exit 1

      - name: Terraform Apply
        if: github.event_name != 'pull_request'
        run: |
          terraform apply -auto-approve -input=false \
            -var="public_access_cidrs=${PUBLIC_ACCESS_CIDRS}" \
            -var="github_actions_role_arn=${ACTIONS_ROLE_ARN}" || exit 1

      - name: Github SHA
        if: github.event_name != 'pull_request'
        run: echo "${GITHUB_SHA}" > commit_sha.txt

      - name: Upload commit SHA as artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: commit-sha
          path: terraform/commit_sha.txt



    